### ISSUE TITLE
Python interfaces problems

### ISSUE THREAD

**Issue by fx1994** [stevenblair/rapid61850#1]
When I use the Python interfaces, when I build the C project, making  errors, I can't get the pyd file.
The errors are like this.
![image](https://cloud.githubusercontent.com/assets/18289144/14286748/b9ff0d2e-fb82-11e5-9bc7-f9f0884a71b0.png)
![image](https://cloud.githubusercontent.com/assets/18289144/14286822/0233a910-fb83-11e5-8cd5-8284347a12a3.png)
![image](https://cloud.githubusercontent.com/assets/18289144/14286836/0e486ce0-fb83-11e5-9b4f-1b809f04b8b7.png)
![image](https://cloud.githubusercontent.com/assets/18289144/14286925/6a3572fa-fb83-11e5-8ac5-648aaab693bc.png)

I suppose there should be an another head file. Could you answer this question for me,please?

Thank you !

**Comment by stevenblair** [comment]
It looks like you are including additional C main files when compiling your project - and these example files are meant for different SCL files. This should be fixed by doing this: right-click on the files in Eclipse > "Resource Configurations" > "Exclude from Build...", and then check the boxes for "Release" or "Debug" or another build.
