### ISSUE TITLE
Problem about scd file

### ISSUE THREAD

**Issue by fx1994** [stevenblair/rapid61850#3]
When I choose a my scd file as an input scd flie to Main.java, and run the Main.java, the error comes like this.
![image](https://cloud.githubusercontent.com/assets/18289144/14343030/c3a16620-fcd0-11e5-99e5-24724d2ea4a4.png)
In this  scd file ,it's an goose output of the float type like this. The last one is the float output from goose , and it leads to an error.
![image](https://cloud.githubusercontent.com/assets/18289144/14343073/1301546e-fcd1-11e5-993f-bf63a5ac3940.png)

How can I fix it? 
Thank you!

**Comment by stevenblair** [comment]
As the error states, the `mag.f` syntax for referencing data attributes is not supported - it's very complex to deal with. Instead, you could edit your SCD file to use `daName="mag"`.

It looks like you are using an RTDS GTNET card as one of the IEDs so, by default, the data type of `mag` only contains `f`. Therefore specifying the higher-level DA will not have a significant impact on your encoded dataset for GOOSE (and would have zero impact for SV). However, for GOOSE I think you will still need to ensure that the RSCAD accepts the updated SCD file with `daName="mag"` - otherwise there could be a mismatch in the dataset encoding/decoding.
